# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'atin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
from PyQt5.QtGui import QImage
from configUI import Ui_Form
import cv2
from info import Ui_Info


class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi()
        self.list_info = []

        for i in range(4):
            info = Ui_Info()
            print(info)
            self.list_info.append(info)
            self.scrollAreaWidgetContents.layout().addWidget(info)

        self.show()
        
    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(1920, 1045)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setAutoFillBackground(True)
        self.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setStyleSheet("background-color: #047c9c")
        self.centralwidget.setObjectName("centralwidget")
        self.count_label = QtWidgets.QLabel(self.centralwidget)
        self.count_label.setGeometry(QtCore.QRect(330, 440, 38, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.count_label.sizePolicy().hasHeightForWidth())
        self.count_label.setSizePolicy(sizePolicy)
        self.count_label.setMaximumSize(QtCore.QSize(38, 72))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.count_label.setFont(font)
        self.count_label.setStyleSheet("background-color: #aaa900;\n"
"")
        self.count_label.setObjectName("count_label")
        self.video_label = QtWidgets.QLabel(self.centralwidget)
        self.video_label.setGeometry(QtCore.QRect(400, 30, 1481, 701))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_label.sizePolicy().hasHeightForWidth())
        self.video_label.setSizePolicy(sizePolicy)
        self.video_label.setText("")
        self.video_label.setPixmap(QtGui.QPixmap("Image/Kokushibo_29.png"))
        self.video_label.setScaledContents(True)
        self.video_label.setObjectName("video_label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(51, 25, 341, 391))
        self.layoutWidget.setMinimumSize(QtCore.QSize(341, 391))
        self.layoutWidget.setMaximumSize(QtCore.QSize(341, 391))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Logo_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Logo_label.sizePolicy().hasHeightForWidth())
        self.Logo_label.setSizePolicy(sizePolicy)
        self.Logo_label.setMinimumSize(QtCore.QSize(339, 191))
        self.Logo_label.setMaximumSize(QtCore.QSize(339, 191))
        self.Logo_label.setText("")
        self.Logo_label.setPixmap(QtGui.QPixmap("Image/Atin.png"))
        self.Logo_label.setScaledContents(True)
        self.Logo_label.setObjectName("Logo_label")
        self.verticalLayout_2.addWidget(self.Logo_label)
        self.widget = QtWidgets.QWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(339, 191))
        self.widget.setMaximumSize(QtCore.QSize(339, 191))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.config_but = QtWidgets.QPushButton(self.widget)
        self.config_but.setEnabled(True)
        self.config_but.setMinimumSize(QtCore.QSize(317, 28))
        self.config_but.setMaximumSize(QtCore.QSize(317, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.config_but.setFont(font)
        self.config_but.setAutoFillBackground(False)
        self.config_but.setStyleSheet("border-radius: 5px;\n"
"background-color: #aaa900;\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/CG.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.config_but.setIcon(icon)
        self.config_but.setObjectName("config_but")
        self.verticalLayout.addWidget(self.config_but)
        self.start_but = QtWidgets.QPushButton(self.widget)
        self.start_but.setMinimumSize(QtCore.QSize(317, 28))
        self.start_but.setMaximumSize(QtCore.QSize(317, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_but.setFont(font)
        self.start_but.setStyleSheet("border-radius: 5px;\n"
"background-color: #aaa900;\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start_but.setIcon(icon1)
        self.start_but.setObjectName("start_but")
        self.verticalLayout.addWidget(self.start_but)
        self.stop_but = QtWidgets.QPushButton(self.widget)
        self.stop_but.setMinimumSize(QtCore.QSize(317, 28))
        self.stop_but.setMaximumSize(QtCore.QSize(317, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stop_but.setFont(font)
        self.stop_but.setStyleSheet("border-radius: 5px;\n"
"background-color: #aaa900;\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_but.setIcon(icon2)
        self.stop_but.setObjectName("stop_but")
        self.verticalLayout.addWidget(self.stop_but)
        self.find_but = QtWidgets.QPushButton(self.widget)
        self.find_but.setMinimumSize(QtCore.QSize(317, 28))
        self.find_but.setMaximumSize(QtCore.QSize(317, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.find_but.setFont(font)
        self.find_but.setStyleSheet("border-radius: 5px;\n"
"background-color: #aaa900;\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.find_but.setIcon(icon3)
        self.find_but.setObjectName("find_but")
        self.verticalLayout.addWidget(self.find_but)
        self.verticalLayout_2.addWidget(self.widget)
        self.car_label = QtWidgets.QLabel(self.centralwidget)
        self.car_label.setGeometry(QtCore.QRect(60, 430, 321, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.car_label.sizePolicy().hasHeightForWidth())
        self.car_label.setSizePolicy(sizePolicy)
        self.car_label.setStyleSheet("border-radius: 5px;")
        self.car_label.setText("")
        self.car_label.setPixmap(QtGui.QPixmap("Image/car.png"))
        self.car_label.setScaledContents(True)
        self.car_label.setObjectName("car_label")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(70, 770, 1801, 201))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1799, 199))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.car_label.raise_()
        self.count_label.raise_()
        self.video_label.raise_()
        self.layoutWidget.raise_()
        self.scrollArea.raise_()
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.count_label.setText(_translate("MainWindow", "0"))
        self.config_but.setText(_translate("MainWindow", "Thiết lập cấu hình"))
        self.start_but.setText(_translate("MainWindow", "Bắt đầu"))
        self.stop_but.setText(_translate("MainWindow", "Kết thúc"))
        self.find_but.setText(_translate("MainWindow", "Tìm kiếm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    
    sys.exit(app.exec_())