# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'info.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import QApplication, QWidget

from PyQt5 import QtWidgets, QtCore,QtGui

class Ui_Info(QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi()
        self.show()
    def setupUi(self):
        self.setObjectName("self")
        self.resize(301, 165)
        self.widget = QtWidgets.QWidget(self)
        self.widget.setGeometry(QtCore.QRect(0, 0, 301, 161))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        font = QtGui.QFont()
        font.setPointSize(10)
        self.image_label = QtWidgets.QLabel(self.widget)
        self.image_label.setGeometry(QtCore.QRect(0, 0, 150, 159))
        self.image_label.setEnabled(True)
        self.image_label.setScaledContents(True)
        self.image_label.setStyleSheet("background-color: #090d09")
        self.image_label.setObjectName("image_label")
        self.horizontalLayout.addWidget(self.image_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_time = QtWidgets.QLabel(self.widget)
        self.label_time.setStyleSheet("background-color: #f9f1ee")
        self.label_time.setObjectName("label_time")
        self.verticalLayout.addWidget(self.label_time)
        self.label_brand = QtWidgets.QLabel(self.widget)
        self.label_brand.setStyleSheet("background-color: #a0dee9")
        self.label_brand.setObjectName("label_brand")
        self.verticalLayout.addWidget(self.label_brand)
        self.label_Bien = QtWidgets.QLabel(self.widget)
        self.label_Bien.setStyleSheet("background-color: #f9f1ee")
        self.label_Bien.setObjectName("label_Bien")
        self.verticalLayout.addWidget(self.label_Bien)
        self.label_color = QtWidgets.QLabel(self.widget)
        self.label_color.setStyleSheet("background-color: #a0dee9")
        self.label_color.setObjectName("label_color")
        self.verticalLayout.addWidget(self.label_color)
        self.label_something = QtWidgets.QLabel(self.widget)
        self.label_something.setStyleSheet("background-color: #f9f1ee")
        self.label_something.setObjectName("label_something")
        self.verticalLayout.addWidget(self.label_something)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.label_time.setFont(font)
        self.label_Bien.setFont(font)
        self.label_color.setFont(font)
        self.label_brand.setFont(font)
        self.label_something.setFont(font)
        self.retranslateUi()
        # QtCore.QMetaObject.connectSlotsByName()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "self"))
        self.image_label.setText(_translate("self", "ảnh"))
        self.label_time.setText(_translate("self", "thời gian"))
        self.label_brand.setText(_translate("self", "hãng"))
        self.label_Bien.setText(_translate("self", "Biển số"))
        self.label_color.setText(_translate("self", "Màu"))
        self.label_something.setText(_translate("self", "Hmm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Info = Ui_Info()
    sys.exit(app.exec_())

